server:
  port: 80

spring:
  application:
    name: cloud-order-feign-service

eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true。
    register-with-eureka: true
    service-url:
      # 集群
      defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka  # 集群版

ribbon:
  #指的是建立连接所用的时间，使用与网络状况正常的情况下，两端连接所用的时间
  ReadTimeout: 5000
  #指的是建立连接后从服务器读取到可用资源所用的时间
  ConnectTimeout: 5000

logging:
  level:
    # feign日志以什么级别监控哪个接口
    com.aote.springcloud.service.PaymentFeignService: debug
