server:
  port: 8001

spring:
  application:
    # 相同业务集群，应用名称必须相同
    name: cloud-payment-hystrix-service

eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true。
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetchRegistry: true
    service-url:
      #单机版
      #defaultZone: http://localhost:7001/eureka
      #集群版
      defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka
  # 修改eureka主机名
  instance:
    instance-id: payment8001 #主机名
    prefer-ip-address: true #显示ip